# Generated by Django 4.0.6 on 2022-07-13 13:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('HIN', 'Hindi'), ('SANSK', 'Sanskrit'), ('SP', 'Spanish'), ('FR', 'French'), ('GR', 'German'), ('EVS', 'Environmental science (EVS)'), ('SCIENCE', 'Science'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('CS', 'Computer science'), ('PSYCH', 'PSYCHOLOGY'), ('SST', 'Social studies / Social science'), ('HIST', 'History'), ('CIV', 'Civics'), ('GEO', 'Geography'), ('ECO', 'Economics'), ('COM', 'Commerce'), ('ACC', 'Accounting'), ('SOC', 'Sociology'), ('HOM', 'Home science'), ('ART', 'Art')], default=None, max_length=1024, null=True),
        ),
    ]
