# Generated by Django 4.0.6 on 2022-08-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoommeeting',
            old_name='join_link',
            new_name='join_url',
        ),
        migrations.RenameField(
            model_name='zoommeeting',
            old_name='start_link',
            new_name='start_url',
        ),
    ]
