# Generated by Django 4.0.6 on 2022-08-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_join_link_zoommeeting_join_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='is_started',
        ),
    ]
