# Generated by Django 4.0.6 on 2022-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tutor_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorship',
            name='status',
            field=models.CharField(choices=[('PNDG', 'Pending'), ('ACPTD', 'Accepted'), ('RJCTD', 'Rejected')], default=None, max_length=12, null=True),
        ),
    ]
