# Generated by Django 4.0.6 on 2022-07-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='join_code',
            field=models.CharField(default=None, editable=False, max_length=10, null=True),
        ),
    ]
