# Generated by Django 4.0.6 on 2022-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_school_join_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachments_key_prefix',
        ),
        migrations.AddField(
            model_name='message',
            name='attachments_folder_prefix',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
