# Generated by Django 4.0.6 on 2022-07-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_school_join_code_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='num_occurences',
        ),
    ]
