# Generated by Django 4.0.6 on 2022-07-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tutorship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=1024, null=True)),
                ('meeting_id', models.CharField(default=None, max_length=32, null=True)),
                ('meeting_password', models.CharField(default=None, max_length=1024, null=True)),
                ('num_occurences', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorship',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='tutorship',
            name='meeting_link',
        ),
        migrations.AlterField(
            model_name='tutorship',
            name='status',
            field=models.CharField(choices=[('PNDG', 'Pending'), ('ACPT', 'Accepted'), ('RJCT', 'Rejected')], default='PNDG', max_length=8),
        ),
        migrations.AddField(
            model_name='tutorship',
            name='zoom_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zoommeeting'),
        ),
    ]
