# Generated by Django 4.0.6 on 2022-07-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_zoommeeting_num_occurences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='zoom_meeting',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zoommeeting'),
        ),
    ]
