# Generated by Django 4.1 on 2022-08-03 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
