# Generated by Django 4.1 on 2022-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='status',
            field=models.CharField(choices=[('PNDG', 'Pending'), ('ACPT', 'Accepted'), ('RJCT', 'Rejected'), ('SUSPND', 'Suspended')], default='PNDG', max_length=8),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
