# Generated by Django 4.0.6 on 2022-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_message_attachments_folder_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='tutorship_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
