# Generated by Django 4.0.6 on 2022-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tutorship_zoom_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorship',
            name='createdd',
            field=models.DateTimeField(auto_created=True, default=None, null=True),
        ),
    ]
