# Generated by Django 4.1 on 2022-08-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tutorship_status_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_uuid', models.CharField(default=None, max_length=36, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tutorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tutorship')),
            ],
        ),
    ]
