# Generated by Django 4.0.6 on 2022-07-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tutorship_createdd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorship',
            old_name='createdd',
            new_name='created',
        ),
    ]
