# Generated by Django 4.0.6 on 2022-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_createdd_tutorship_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='created',
            field=models.DateTimeField(auto_created=True, default=None, editable=False, null=True),
        ),
    ]
