# Generated by Django 4.1 on 2022-08-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tutorshipreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='status',
            field=models.CharField(choices=[('PNDG', 'Pending'), ('ACPT', 'Active'), ('RJCT', 'Rejected'), ('SUSPND', 'Suspended')], default='PNDG', max_length=8),
        ),
        migrations.AlterField(
            model_name='tutorshipreport',
            name='tutorship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tutorship'),
        ),
    ]
