# Generated by Django 4.1 on 2022-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tutorship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='age',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='highest_educational_level',
            field=models.CharField(choices=[('10S', '10th standard'), ('12S', '12th standard'), ('BACH', "Bachelor's"), ('MSPLUS', "Master's or above")], default=None, max_length=12, null=True),
        ),
    ]
