# Generated by Django 4.1 on 2022-08-09 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tutor_age_tutor_highest_educational_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='age',
            field=models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
