# Generated by Django 4.0.6 on 2022-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tutorship_tutorship_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
