# Generated by Django 4.0.6 on 2022-07-31 13:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tutorship_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('STATE', 'State board'), ('ICSE', 'ICSE'), ('ISC', 'ICSE / ISC'), ('IGCSE', 'IGCSE'), ('IB', 'IB'), ('OTHER', 'Other')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('NS', 'Nursery'), ('KG', 'Kindergarten'), ('01G', 'First grade'), ('02G', 'Second grade'), ('03G', 'Third grade'), ('04G', 'Fourth grade'), ('05G', 'Fifth grade'), ('06G', 'Sixth grade'), ('07G', 'Seventh grade'), ('08G', 'Eighth grade'), ('09G', 'Ninth grade'), ('10G', 'Tenth grade'), ('11G', 'Eleventh grade'), ('12G', 'Twelfth grade')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='boards',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CBSE', 'CBSE'), ('STATE', 'State board'), ('ICSE', 'ICSE'), ('ISC', 'ICSE / ISC'), ('IGCSE', 'IGCSE'), ('IB', 'IB'), ('OTHER', 'Other')], default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='grades',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NS', 'Nursery'), ('KG', 'Kindergarten'), ('01G', 'First grade'), ('02G', 'Second grade'), ('03G', 'Third grade'), ('04G', 'Fourth grade'), ('05G', 'Fifth grade'), ('06G', 'Sixth grade'), ('07G', 'Seventh grade'), ('08G', 'Eighth grade'), ('09G', 'Ninth grade'), ('10G', 'Tenth grade'), ('11G', 'Eleventh grade'), ('12G', 'Twelfth grade')], default=None, max_length=128, null=True),
        ),
    ]
