# Generated by Django 4.0.6 on 2022-07-07 15:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('name_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('HIN', 'Hindi'), ('SANSK', 'Sanskrit'), ('SP', 'Spanish'), ('EVS', 'Environmental science'), ('SCIENCE', 'Combined sciences'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('CS', 'Computer science'), ('PSYCH', 'PSYCHOLOGY'), ('SST', 'Social studies / Social science'), ('HIST', 'History'), ('CIV', 'Civics'), ('GEO', 'Geography'), ('ECO', 'Economics'), ('COM', 'Commerce'), ('HOM', 'Home science'), ('ART', 'Art')], max_length=8)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.platformuser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('STATE', 'State board'), ('ICSE', 'ICSE'), ('ISC', 'ISC'), ('IGCSE', 'IGCSE'), ('IB', 'IB'), ('OTHER', 'Other')], max_length=16)),
                ('grade', models.CharField(choices=[('NS', 'NURSEY'), ('KG', 'KINDERGARTEN'), ('1', 'FIRST GRADE'), ('2', 'SECOND GRADE'), ('3', 'THIRD GRADE'), ('4', 'FOURTH GRADE'), ('5', 'FIFTH GRADE'), ('6', 'SIXTH GRADE'), ('7', 'SEVENTH GRADE'), ('8', 'EIGHTH GRADE'), ('9', 'NINTH GRADE'), ('10', 'TENTH GRADE'), ('11', 'ELEVENTH GRADE'), ('12', 'TWELFTH GRADE')], max_length=2)),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('HIN', 'Hindi'), ('SANSK', 'Sanskrit'), ('SP', 'Spanish'), ('EVS', 'Environmental science'), ('SCIENCE', 'Combined sciences'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('CS', 'Computer science'), ('PSYCH', 'PSYCHOLOGY'), ('SST', 'Social studies / Social science'), ('HIST', 'History'), ('CIV', 'Civics'), ('GEO', 'Geography'), ('ECO', 'Economics'), ('COM', 'Commerce'), ('HOM', 'Home science'), ('ART', 'Art')], max_length=8)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.platformuser')),
            ],
        ),
    ]
